config = dict(
    name="cifar10",
    dataset="cifar10",
    data_root="cifar",
    n_steps=200_000,
    batch_size=64,
    num_workers=8,
    image_size=32,
    lr=1e-4,
    weight_decay=0.0,
    grad_clip=5.0,
    mixed_precision='bf16',
    scheduler=dict(warmup_steps=2500, min_lr_ratio=0.1),
    log_step=500,
    sample_step=500,
    sample_nrow=10,
    sample_classes=None,
    model=dict(
        input_size=32,
        patch_size=2,
        in_channels=3,
        dim=512,
        depth=12,
        num_heads=8,
        num_classes=10,
        max_cfg=7.5,
    ),
    meanflow=dict(
        mode="i-meanflow",
        normalizer=["minmax", None, None],
        time_dist=["lognorm", -0.4, 1.0],
        cfg_ratio=0.10,
        cfg_scale=[1.0, 7.5],
        cfg_scale_ratio=0.75,
        adaptive_l2_gamma=0.0,
        adaptive_l2_c=1e-2,
    ),
)
