latent_factor = 0.18215

config = dict(
    name="imagenet_latent",
    dataset="imagenet",
    data_root="/home/jerry/Projects/Dataset/imagenet/train",
    n_steps=200_000,
    batch_size=64,
    num_workers=8,
    image_size=256,
    lr=1e-4,
    weight_decay=0.0,
    grad_clip=5.0,
    mixed_precision='bf16',
    scheduler=dict(warmup_steps=2500, min_lr_ratio=0.1),
    log_step=1000,
    sample_step=1000,
    sample_nrow=5,
    sample_classes=[157, 281, 1, 404, 805],
    latent=True,
    vae_id="stabilityai/sd-vae-ft-mse",
    latent_factor=latent_factor,
    model=dict(
        input_size=32,
        patch_size=2,
        in_channels=4,
        dim=512,
        depth=12,
        num_heads=8,
        num_classes=1000,
        max_cfg=7.5,
    ),
    meanflow=dict(
        mode="i-meanflow",
        normalizer=["mean_std", 0.0, 1 / latent_factor],
        time_dist=["lognorm", -0.4, 1.0],
        cfg_ratio=0.10,
        cfg_scale=[1.0, 7.5],
        cfg_scale_ratio=0.75,
        adaptive_l2_gamma=0.0,
        adaptive_l2_c=1e-2,
    ),
)
